<?php

namespace Database\Seeders;

use App\Enums\ApprovalMode;
use App\Enums\AssetSource;
use App\Enums\AssetType;
use App\Enums\CampaignStatus;
use App\Enums\ConnectionStatus;
use App\Enums\Platform;
use App\Enums\PostStatus;
use App\Models\Asset;
use App\Models\Campaign;
use App\Models\Client;
use App\Models\Post;
use App\Models\PostActivityLog;
use App\Models\PostComment;
use App\Models\PostTarget;
use App\Models\SocialAccount;
use App\Models\User;
use Illuminate\Database\Seeder;

/**
 * Seeds additional demo content (social accounts, campaigns, assets, posts + targets, and
 * comment/activity-log history) for the sample clients created by `ClientSeeder`, so the local
 * dev/demo database has richer, more realistic data to click through beyond the bare-minimum
 * fixtures. Idempotent (`updateOrCreate`), safe to re-run on every seed.
 */
class DemoContentSeeder extends Seeder
{
    public function run(): void
    {
        $owner = User::firstWhere('email', 'test@example.com');

        foreach (['Recommendo', 'Frzn'] as $clientName) {
            $client = Client::firstWhere('name', $clientName);

            if (! $client || ! $owner) {
                continue;
            }

            $this->seedForClient($client, $owner);
        }
    }

    private function seedForClient(Client $client, User $owner): void
    {
        $socialAccounts = collect([
            [Platform::Instagram, '@'.str($client->name)->slug()],
            [Platform::TikTok, '@'.str($client->name)->slug().'.official'],
            [Platform::LinkedIn, str($client->name)->slug()],
        ])->map(function (array $definition) use ($client) {
            [$platform, $handle] = $definition;

            return SocialAccount::updateOrCreate(
                ['org_id' => $client->org_id, 'client_id' => $client->id, 'handle' => $handle],
                [
                    'platform' => $platform,
                    'display_name' => $client->name.' '.$platform->label(),
                    'timezone' => 'America/New_York',
                    'language' => $client->default_language ?? 'en',
                    'country' => 'US',
                    'connection_status' => ConnectionStatus::Connected,
                ]
            );
        });

        $campaigns = collect([
            ['name' => 'Spring Refresh', 'status' => CampaignStatus::Completed, 'offsetStart' => -8, 'offsetEnd' => -4],
            ['name' => 'Summer Push', 'status' => CampaignStatus::Active, 'offsetStart' => -1, 'offsetEnd' => 2],
            ['name' => 'Holiday Countdown', 'status' => CampaignStatus::Planning, 'offsetStart' => 2, 'offsetEnd' => 4],
        ])->map(fn (array $definition) => Campaign::updateOrCreate(
            ['org_id' => $client->org_id, 'client_id' => $client->id, 'name' => $definition['name']],
            [
                'status' => $definition['status'],
                'start_date' => now()->addWeeks($definition['offsetStart'])->toDateString(),
                'end_date' => now()->addWeeks($definition['offsetEnd'])->toDateString(),
                'goal' => 'Demo campaign generated by DemoContentSeeder for '.$client->name.'.',
                'notes' => null,
            ]
        ));

        $assets = $campaigns->flatMap(fn (Campaign $campaign) => collect(range(1, 2))->map(
            fn (int $index) => Asset::updateOrCreate(
                [
                    'org_id' => $client->org_id,
                    'client_id' => $client->id,
                    'campaign_id' => $campaign->id,
                    'url' => "https://picsum.photos/seed/{$client->id}-{$campaign->id}-{$index}/800/800",
                ],
                [
                    'source' => AssetSource::Url,
                    'type' => AssetType::Image,
                    'uploaded_by' => $owner->id,
                    'rights' => 'Stock placeholder — demo use only.',
                ]
            )
        ));

        $postDefinitions = [
            ['status' => PostStatus::Published, 'caption' => 'Look back at our '.$client->name.' campaign win.', 'daysOffset' => -6],
            ['status' => PostStatus::Scheduled, 'caption' => 'Upcoming feature drop for '.$client->name.'.', 'daysOffset' => 3],
            ['status' => PostStatus::WaitingClient, 'caption' => 'Draft awaiting client sign-off.', 'daysOffset' => 5],
            ['status' => PostStatus::Draft, 'caption' => 'Early idea for the next push.', 'daysOffset' => 10],
        ];

        foreach ($postDefinitions as $index => $definition) {
            $campaign = $campaigns[$index % $campaigns->count()];
            $socialAccount = $socialAccounts[$index % $socialAccounts->count()];
            $asset = $assets[$index % $assets->count()];

            $post = Post::updateOrCreate(
                ['org_id' => $client->org_id, 'client_id' => $client->id, 'master_caption' => $definition['caption']],
                [
                    'campaign_id' => $campaign->id,
                    'created_by' => $owner->id,
                    'status' => $definition['status'],
                    'approval_mode' => ApprovalMode::ClientRequired,
                    'hashtags' => ['#'.str($client->name)->slug(), '#demo'],
                    'music' => null,
                    'location' => null,
                    'checklist_snapshot' => null,
                ]
            );

            $post->assets()->syncWithoutDetaching([$asset->id]);

            PostTarget::updateOrCreate(
                ['post_id' => $post->id, 'social_account_id' => $socialAccount->id],
                [
                    'scheduled_local_date' => now()->addDays($definition['daysOffset'])->toDateString(),
                    'scheduled_local_time' => '10:00:00',
                    'scheduled_at_utc' => now()->addDays($definition['daysOffset'])->setTime(14, 0),
                ]
            );

            PostComment::updateOrCreate(
                ['post_id' => $post->id, 'user_id' => $owner->id, 'body' => 'Internal note: this one needs a final review pass.'],
                ['internal_only' => true]
            );

            PostComment::updateOrCreate(
                ['post_id' => $post->id, 'user_id' => $owner->id, 'body' => 'Looking good — thanks for the quick turnaround!'],
                ['internal_only' => false]
            );

            PostActivityLog::updateOrCreate(
                ['post_id' => $post->id, 'user_id' => $owner->id, 'from_status' => PostStatus::Draft, 'to_status' => $definition['status']],
                ['note' => 'Seeded activity log entry for demo content.']
            );
        }
    }
}
